# Generated by Django 5.2.1 on 2025-06-03 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='cpf')),
                ('numero', models.IntegerField(verbose_name='número para contato')),
                ('data_nascimento', models.DateField(verbose_name='data de nascimento')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('cep', models.CharField(max_length=8, verbose_name='cep')),
                ('rua', models.CharField(max_length=100, verbose_name='rua')),
                ('cidade', models.CharField(max_length=35, verbose_name='cidade')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], verbose_name='estado')),
                ('tipo', models.CharField(choices=[('FUNCIONARIO', 'Funcionario'), ('LOCADOR', 'Locador')], null=True, verbose_name='tipo')),
                ('observacoes', models.TextField(verbose_name='observações')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50, verbose_name='cargo')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='salário')),
                ('pis', models.CharField(max_length=13, verbose_name='pis')),
                ('entrada', models.DateField(auto_now_add=True, verbose_name='data de entrada')),
                ('saida', models.DateField(verbose_name='data de saida')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastros.cliente', verbose_name='cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Locador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='valor do aluguel')),
                ('inicio_contrato', models.DateField(verbose_name='inicio do contrato')),
                ('fim_contrato', models.DateField(verbose_name='fim do contrato')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastros.cliente', verbose_name='locador')),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimento', models.CharField(max_length=50, unique=True, verbose_name='procedimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='valor')),
                ('tempo_medio', models.DurationField(blank=True, null=True, verbose_name='Tempo Médio do Procedimento')),
                ('profissionais', models.ManyToManyField(related_name='profissional_que_realiza', to='cadastros.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='data e hora do agendamento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.cliente', verbose_name='cliente')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.procedimento', verbose_name='procedimento')),
            ],
        ),
    ]
