# Generated by Django 5.2.1 on 2025-06-03 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimento',
            name='profissionais',
        ),
        migrations.AddField(
            model_name='procedimento',
            name='profissionais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.funcionario', verbose_name='funcionarios'),
        ),
    ]
