# Generated by Django 5.2.1 on 2025-06-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_procedimento_profissionais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.CharField(verbose_name='número para contato'),
        ),
    ]
