# Generated by Django 5.2.1 on 2025-06-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_cliente_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(max_length=8, null=True, verbose_name='cep'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(max_length=35, null=True, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(null=True, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rua',
            field=models.CharField(max_length=100, null=True, verbose_name='rua'),
        ),
    ]
