# Generated by Django 5.2.1 on 2025-06-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_cliente_cep_alter_cliente_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='entrada',
            field=models.DateField(verbose_name='data de entrada'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='saida',
            field=models.DateField(blank=True, verbose_name='data de saida'),
        ),
        migrations.AlterField(
            model_name='locador',
            name='fim_contrato',
            field=models.DateField(blank=True, verbose_name='fim do contrato'),
        ),
    ]
