# Generated by Django 5.2.1 on 2025-06-12 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Pessoa',
        ),
        migrations.RenameField(
            model_name='locador',
            old_name='cliente',
            new_name='pessoa',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='cliente',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerencia.pessoa', verbose_name='pessoa'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='pessoa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerencia.pessoa', verbose_name='pessoa'),
        ),
    ]
